Makefile
README.md
package-lock.json

Also specify Node version to use. This helps avoid hard-to-reproduce bugs.

Use npm ci for consistent package versions.

---

dist/index.html
src/tsx/liveScreen.tsx
src/tsx/main.tsx

Right now we only display the number of times
the space bar has been pressed, to exercise
handling key presses in some way.
I have no idea what I'm doing here with regards to
both typescript and react, so I am prepared for
extensive reworking after comments.

Basic component for the live screen.

---

src/tsx/coreConnection.tsx
src/tsx/liveScreen.tsx
src/tsx/main.tsx

Create an interface and dummy implementation
of a connection to the core, for development.
Later, a real implementation will be created
that will communicate with the core using
a websocket.

Abstract away connection to the core

---

src/less/main.module.less
src/tsx/coreConnection.tsx
src/tsx/liveScreen.tsx
src/tsx/main.tsx

Also make a component containing the header and
the live screen, for better handling of state.

Add input to select core address

---

src/tsx/coreConnection.tsx
src/tsx/liveScreen.tsx

This is better than implementing our own event system.

Have CoreConnection be an EventTarget

---

src/less/timeline.module.less
src/tsx/coreConnection.tsx
src/tsx/liveScreen.tsx
src/tsx/timeline.tsx
src/tsx/types.tsx
tsconfig.json

Update DummyCoreConnection to send a linear timeline,
and step forward in it. Update Timeline to show it
as text.

Make the timeline slightly more realistic

---

src/tsx/coreConnection.tsx
src/tsx/coreMessages.tsx
src/tsx/statusView/audioEffect.tsx
src/tsx/statusView/statusView.tsx
src/tsx/types.tsx

See other PRs as well: https://github.com/kulturkrock/screencrash-core/pull/14 and https://github.com/kulturkrock/screencrash-components/pull/67

Add support for effects in real core connection

---

browser-sync.config.js

See documentation [here](https://browsersync.io/docs/options#option-ghostMode).

Don't mirror click events between UI browsers

---

src/less/statusView.module.less
src/tsx/statusView/videoEffect.tsx
src/tsx/types.tsx

PR in components: https://github.com/kulturkrock/screencrash-components/pull/71

Add video preview status

---

src/tsx/coreConnection.tsx
src/tsx/liveScreen.tsx
src/tsx/timeline.tsx
src/tsx/types.tsx

The user can now choose which path to go down with the keyboard.

Display and choose between branches

---

src/tsx/pdfViewer.tsx

Add PgDown and PgUp to scroll in script view

Scroll in script

---

src/less/liveScreen.module.less
src/tsx/coreConnection.tsx
src/tsx/liveScreen.tsx

See https://github.com/kulturkrock/screencrash-core/pull/29

Improve navigation

---

src/less/timeline.module.less
src/tsx/liveScreen.tsx
src/tsx/timeline.tsx
src/tsx/types.tsx

Show actions for nodes

---

src/tsx/componentView.tsx
src/tsx/statusView.tsx

Fix eslint warning

---

src/tsx/componentView.tsx
src/tsx/coreConnection.tsx
src/tsx/liveScreen.tsx
src/tsx/statusView.tsx
src/tsx/types.tsx

Add changes to match https://github.com/kulturkrock/screencrash-core/pull/36. This is just setting up to be able to add component-specific views in the future (e.g. for inventory)

Update component sync

---

src/less/components/inventory.module.less
src/less/statusView.module.less
src/tsx/components/inventory.tsx
src/tsx/coreConnection.tsx
src/tsx/liveScreen.tsx
src/tsx/statusView.tsx

Add inventory view in UI

---

src/tsx/components/inventory.tsx

Updates for https://github.com/kulturkrock/screencrash-components/pull/92

Add support for dynamic currency in UI

---

src/less/timeline.module.less
src/tsx/timeline.tsx
src/tsx/types.tsx

This makes it easier to find the line in the script.

Show line numbers in timeline

---

src/less/shortcutView.module.less
src/tsx/coreConnection.tsx
src/tsx/liveScreen.tsx
src/tsx/shortcutView.tsx
src/tsx/statusView.tsx

Add button to go straight to a node, inserting it to the history in place.

Add goto node button

---

src/tsx/components/inventory.tsx
src/tsx/shortcutView.tsx

This makes them easier to find quickly.

Sort items, achievements and node dropdown
